Adding security scan to main from feature

diff --git a/.github/workflows/ci-frontend.yml b/.github/workflows/ci-frontend.yml
--- a/.github/workflows/ci-frontend.yml
+++ b/.github/workflows/ci-frontend.yml
@@ -19,7 +19,68 @@ env:
 
 
 jobs:
-  image-build-push-frontend:
+  secret-scan:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 
+      - name: Scan for Secrets in Github
+        uses: gitleaks/gitleaks-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  Build-and-scan:
+    runs-on: ubuntu-latest
+    needs: secret-scan
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Lint Dockerfile
+        uses: hadolint/hadolint-action@v3.1.0
+        with:
+          dockerfile: apps/frontend/Dockerfile
+          failure-threshold: error   # only fail on errors
+      - name: npm audit
+        run: |
+          cd apps/frontend
+          npm install
+          npm audit --audit-level=critical
+
+      - name: Authenticate to Google Cloud
+        id: auth
+        uses: google-github-actions/auth@v2
+        with:
+          workload_identity_provider: '${{secrets.WIP}}'
+          service_account: '${{secrets.GCPSA}}'
+
+      - name: Install gcloud
+        uses: google-github-actions/setup-gcloud@v3
+      
+      - name: Docker Configuration
+        run:
+          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
+
+      - name: Build Docker image
+        run: |
+          docker build \
+          -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:${{ github.sha }} \
+          -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:latest \
+          ./apps/frontend
+
+      - name: Scan image with Trivy
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:${{ github.sha }}
+          format: 'table'
+          exit-code: '1'
+          severity: 'CRITICAL'
+          ignore-unfixed: true
+
+
+  image-push-frontend:
     runs-on: ubuntu-latest
 
     steps:
@@ -54,6 +115,27 @@ jobs:
           docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/${{ env.IMAGE_NAME }}:latest
 
 
+# ── Job 4 — Update GitOps ─────────────────────────
+  update-gitops:
+    name: Update GitOps Repo
+    runs-on: ubuntu-latest
+    needs: image-push-frontend
+    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+
+    steps:
+      - name: Update image tag
+        run: |
+          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/sourav-m619/cloudstore-gitops.git
+          cd cloudstore-gitops
+
+          sed -i "s|image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:.*|image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloudstore-image-repo/frontend:${{ github.sha }}|g" \
+            Kubernetes/frontend/deployment.yaml
+
+          git config user.email "github-actions@github.com"
+          git config user.name "GitHub Actions"
+          git add .
+          git commit -m "Update frontend image to ${{ github.sha }}" || echo "No changes"
+          git push
 
 
 
